# Generated by Django 5.0.6 on 2026-07-16 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("dress", "Dress"),
                            ("outerwear", "Outerwear"),
                            ("shoes", "Shoes"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=40)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("mild", "Mild"),
                            ("cold", "Cold"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                            ("work", "Work"),
                            ("sport", "Sport"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothing_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WornLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worn_on", models.DateField()),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                            ("work", "Work"),
                            ("sport", "Sport"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="worn_logs", to="wardrobe.clothingitem"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worn_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-worn_on"],
            },
        ),
    ]
