# Generated by Django 5.0.6 on 2026-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
